/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StakingRouteImport } from './routes/staking'
import { Route as ClaimingRouteImport } from './routes/claiming'
import { Route as IndexRouteImport } from './routes/index'

const StakingRoute = StakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimingRoute = ClaimingRouteImport.update({
  id: '/claiming',
  path: '/claiming',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claiming': typeof ClaimingRoute
  '/staking': typeof StakingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claiming': typeof ClaimingRoute
  '/staking': typeof StakingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claiming': typeof ClaimingRoute
  '/staking': typeof StakingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/claiming' | '/staking'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/claiming' | '/staking'
  id: '__root__' | '/' | '/claiming' | '/staking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimingRoute: typeof ClaimingRoute
  StakingRoute: typeof StakingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claiming': {
      id: '/claiming'
      path: '/claiming'
      fullPath: '/claiming'
      preLoaderRoute: typeof ClaimingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimingRoute: ClaimingRoute,
  StakingRoute: StakingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
